### PR TITLE
updated to work with Django 1.9

### PR DESCRIPTION
**Pull request by willseward**

### CODE REVIEW

**Comment by bufke** [comment]
Do you want to take this project over? I'm not using it at all these days. I think it should be redone using hstore ideally.

**Comment by willseward** [comment]
If you aren't maintaining it, I'd actually be happy taking it over!

**Comment by bufke** [comment]
Ok added you to the project. Do you have a pypi username?

**Comment by willseward** [comment]
Yes, it's willseward.

Do you want me to keep the repo under your username, or do you want me to transfer it to mine?

**Comment by bufke** [comment]
Up to you on the username. I added you on pypi.

**Comment by bufke** [comment]
I removed this project from the demo on report builder. The custom field tests were broken anyway. Do you want to take on fixing those? Otherwise I'll just keep them removed.

**Comment by willseward** [comment]
I can't provide a timeline for the fixes, so go ahead and keep them removed.

**Pull request merged**
